# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  children-max:
    type: int
    default: 20
    description: |
      Maximum amount of child process created to manage authentication.
  children-startup:
    type: int
    default: 0
    description: |
      Initial amount of child process to manage  authentication created at startup.
  children-idle:
    type: int
    default: 1
    description: |
      Amount of idle child process to manage  authentication that must be available at any time.
  vault-filepath:
    type: string
    default: "/etc/squid-auth/password-file"
    description: |
      Path where usernames and passwords will be stored.
  nonce-garbage-interval:
    type: int
    default: 5
    description: |
      Specifies the interval in minutes that nonces that have been issued to client_agent's are checked for validity.
      Required if authentication_type is "digest".
  nonce-max-duration:
    type: int
    default: 30
    description: |
      Specifies the maximum length of time in minutes a given nonce will be valid for.
      Required if authentication_type is "digest".
  nonce-max-count:
    type: int
    default: 50
    description: |
      Specifies the maximum number of times a given nonce can be used.
      Required if authentication_type is "digest".
  realm:
    type: string
    default: "squid"
    description: |
      Name of the HTTP authentication realm.
      Required if authentication_type is "digest".
  authentication-type:
    type: string
    default: "digest"
    description: |
      Specifies which authentication type Squid will provide. Currently supports "basic" and "digest".
      Only one authentication type is active at a time.
